apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: podlog
  namespace: kube-system
  labels:
    k8s-app: podlog
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: podlog
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: podlog
        image: areller/podlog:latest
        imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 30